config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('control-admin/', admin.site.urls),
    path('', include('shops.urls', namespace="shops")),
    path('summernote/', include('django_summernote.urls')),
    path('products/', include('products.urls', namespace="products")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('account/', include('users.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('info/', include('core.urls', namespace="core")),
    path('about/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import dashboard

app_name = "core"

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"),
]

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path('status/<int:pk>/', views.status, name="status"),
    path('create/<int:pk>/', views.OrderCreateView.as_view(), name="order_create"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('<int:pk>/<slug:slug>/', views.ProductDetailView.as_view(), name="detail"),
    path('create/<int:pk>/', views.ProductCreateView.as_view(),
         name="product-create"),
    path('edit/<int:pk>/', views.ProductEditView.as_view(), name="product-edit"),
    path('delete/<int:pk>/', views.ProductDeleteView.as_view(),
         name="product-delete"),
    path('category/<slug:category>/',
         views.CategoryView.as_view(), name="category"),
    path('search/', views.SearchView.as_view(), name="search"),
]

products/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from shops.models import Category
from django.core.exceptions import ValidationError
from core.compress import compress


class Product(models.Model):
    shop = models.ForeignKey(
        "shops.Shop", related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=90)
    slug = models.SlugField(blank=True)
    price = models.PositiveIntegerField()
    discounted_price = models.PositiveIntegerField(blank=True, null=True)
    sub_title = models.TextField(blank=True, max_length=300)
    description = models.TextField(blank=True, max_length=3000)
    main_image = models.ImageField(
        upload_to="products/")
    image1 = models.ImageField(upload_to="products/", blank=True)
    image2 = models.ImageField(upload_to="products/", blank=True)
    image3 = models.ImageField(upload_to="products/", blank=True)
    image4 = models.ImageField(upload_to="products/", blank=True)
    in_stock = models.BooleanField(default=True)
    sku = models.CharField(blank=True, max_length=50)
    brand = models.CharField(max_length=60, blank=True)
    category = models.ForeignKey(
        "shops.Category",  related_name="products", on_delete=models.DO_NOTHING)
    date_added = models.DateField(default=timezone.now)
    date_edited = models.DateField(auto_now=True)
    featured = models.BooleanField(default=False)
    block = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk": self.pk, "slug": self.slug})

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.discounted_price:
            if self.discounted_price > self.price:
                self.discounted_price = None
        try:
            product = Product.objects.get(pk=self.pk)
        except Product.DoesNotExist:
            self.slug = slugify(self.name)

        self.main_image = compress(self.main_image)

        if self.image1:
            self.image1 = compress(self.image1)

        if self.image2:
            self.image2 = compress(self.image2)

        if self.image3:
            self.image3 = compress(self.image3)

        if self.image4:
            self.image4 = compress(self.image4)

        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-pk', ]

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import DetailView, TemplateView, CreateView, UpdateView, DeleteView, ListView
from . import models
from shops.models import Shop, Category
from django.db.models import Q
from django.contrib import messages


class ProductDeleteView(DeleteView):
    model = models.Product
    success_url = "core:dashboard"
    template_name = "products/product_confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        messages.success(
            self.request, 'Your product was successfully deleted')
        return redirect(reverse(self.success_url))


class ProductCreateView(CreateView):
    model = models.Product
    fields = ["name", "sub_title", "description", "price", "discounted_price", "main_image", "image1",
              "image2", "image3", "image4", "in_stock", "sku", "brand", "category", ]
    template_name = "products/product_create.html"

    def render_to_response(self, context, **response_kwargs):
        shop = get_object_or_404(Shop, pk=self.kwargs.get('pk'))
        if shop.limited:
            if shop.products.count() >= 20:
                return redirect(reverse("core:dashboard"))
        return super().render_to_response(context, **response_kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        shop = get_object_or_404(Shop, pk=self.kwargs.get('pk'))
        self.object.shop = shop
        self.object.save()
        messages.success(
            self.request, f'{self.object.name} was successfully added to Trade Nepal.')
        return redirect(self.get_success_url())


class ProductEditView(UpdateView):
    model = models.Product
    fields = ["name", "description", "price", "discounted_price", "main_image", "image1",
              "image2", "image3", "image4", "in_stock", "sku", "brand", "category", ]
    template_name = "products/product_edit.html"

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, f'Your product was successfully edited.')
        return redirect(self.get_success_url())


class ProductDetailView(DetailView):
    model = models.Product
    template_name = "products/product_detail.html"
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context["product"]
        shop_products = models.Product.objects.filter(
            shop=product.shop).filter(block=False)
        context["shop_products"] = shop_products
        return context


class SearchView(ListView):
    template_name = "products/search.html"
    paginate_by = 20
    context_object_name = "products"

    def get_queryset(self):
        sort = self.request.GET.get('sort', '')
        category = self.request.GET.get('category', 'all')
        products = models.Product.objects.filter(
            Q(shop__name__icontains=self.request.GET.get('term', '')) |
            Q(name__icontains=self.request.GET.get('term', '')) |
            Q(sub_title__icontains=self.request.GET.get('term', '')) |
            Q(description__icontains=self.request.GET.get('term', ''))
        ).filter(block=False)
        if category != "all":
            try:
                item = get_object_or_404(Category, slug=category)
                products = products.filter(category=item)
            except Exception:
                pass

        if sort == "latest":
            products = products.order_by('-date_added')
        elif sort == "price high to low":
            products = products.order_by('-price')
        elif sort == "price low to high":
            products = products.order_by('price')
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context["categories_list"] = categories
        return context


class CategoryView(ListView):
    template_name = "products/category.html"
    paginate_by = 20
    context_object_name = "products"

    def get_queryset(self):
        sort = self.request.GET.get('sort', '')
        item = get_object_or_404(Category, slug=self.kwargs['category'])
        products = models.Product.objects.filter(
            category=item).filter(block=False)

        if sort == "latest":
            products = products.order_by('-date_added')
        elif sort == "price high to low":
            products = products.order_by('-price')
        elif sort == "price low to high":
            products = products.order_by('price')
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context["categories_list"] = categories
        context["category"] = self.kwargs['category']

        return context

templates/products/category.html
{% extends 'base.html' %}
{% load static %}
{% load remove_dash %}

{% block title %}
{{category|remove_dash|title}} Category
{% endblock title %}

{% block content %}
<section class="shop-list-v3-page">
    <div class="container">
        <div class="heading-sub">
            <h3 class="pull-left">{{category|remove_dash|title}}</h3>
            <div class="clearfix"></div>
            <h5>Total {{page_obj.paginator.count}} results</h5>
        </div>

        <div class="widget-product-list">
            <div class="row">

                <div class="col-md-12">
                    <div class="filter-block bd" style="padding-top:0 !important;">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="box box-view">

                                    <div class="box sort">
                                        <span>&nbsp;&nbsp;&nbsp;&nbsp;Change Category:</span>
                                        <button class="dropdown-toggle" type="button" data-toggle="dropdown" id="menu2">
                                            <span class="dropdown-label">{{category|title|remove_dash}}</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu2">

                                            {% for category in categories_list %}
                                            <li><a href="{% url 'products:category' category.slug %}"
                                                    title="">{{category.title}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-7 margin-top3">

                                <div class="box sort pull-right">
                                    <span>Sort by:</span>
                                    <button class="dropdown-toggle" type="button" data-toggle="dropdown" id="menu2">
                                        <span
                                            class="dropdown-label">{% if request.GET.sort %}{{request.GET.sort|title}}{% else %}Relevance{% endif %}</span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="menu2">
                                        <li><a href="?category={{request.GET.category}}&sort=relevance&term={{request.GET.term}}&page=1"
                                                title="">Relevance</a></li>
                                        <li><a href="?category={{request.GET.category}}&sort=latest&term={{request.GET.term}}&page=1"
                                                title="">Latest</a></li>
                                        <li><a href="?category={{request.GET.category}}&sort=price high to low&term={{request.GET.term}}&page=1"
                                                title="">Price: High to Low</a></li>
                                        <li><a href="?category={{request.GET.category}}&sort=price low to high&term={{request.GET.term}}&page=1"
                                                title="">Price: Low to High</a></li>
                                    </ul>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <div class="prod-fea-list">
                            <div class="row">
                                {% for product in products %}
                                {% include 'partials/_product.html' with type='featured' %}
                                {% endfor %}
                            </div>
                            <div class="product-pagination">
                                {% if is_paginated %}
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li><a
                                            href="?category={{request.GET.category}}&sort={{request.GET.sort}}&page={{ page_obj.previous_page_number }}&term={{request.GET.term}}">&laquo;</a>
                                    </li>
                                    {% else %}
                                    <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                    <li><a
                                            href="?category={{request.GET.category}}&sort={{request.GET.sort}}&page={{ i }}&term={{request.GET.term}}">{{ i }}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li><a
                                            href="?category={{request.GET.category}}&sort={{request.GET.sort}}&page={{ page_obj.next_page_number }}&term={{request.GET.term}}">&raquo;</a>
                                    </li>
                                    {% else %}
                                    <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock content %}

{% block banner-part-later %}

<div class="widget-banner">
    <a href="#" class="images"><img src="{% static 'img/products/banner-v2.png' %}" alt="images"
            class="img-responsive"></a>
    <div class="banner-text">
        <h2>New Dokans</h2>
        <p>Contact them directly</p>
    </div>
    <div class="banner-button">
        <a class="btn-getit">Yes, Okay!</a>
    </div>
</div>
{% endblock banner-part-later %}

templates/products/product_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Delete Product
{% endblock title %}

{% block content %}
<div class="container text-center my-5">
    <br>
    <br>
    <h1 class="my-2">Delete your product</h1>

    <br>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if request.user.pk == product.shop.owner.pk %}
            <div class="card">
                <h4>Do you want to delete "{{product.name}}"?</h4>
                <br>
                <form enctype="multipart/form-data" method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="btn-order py-0">
                </form>
                <br>

            </div>
            {% else %}
            <h4>You can't delete the product now. Please contact the website administrator.</h4>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/products/product_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Product
{% endblock title %}

{% block content %}
<div class="container text-center my-5">
    <br>
    <br>
    <h1 class="my-2">Add your product</h1>

    <br>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if request.user.is_seller == True %}
            <div class="card">
                <form enctype="multipart/form-data" method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Add Product" class="btn-order py-0">
                </form>
                <br>

            </div>
            {% else %}
            <h4>You can't add your product now. Please contact the website administrator.</h4>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{product.name}}
{% endblock title %}

{% block meta %}
    <!-- Primary Meta Tags -->
<meta name="title" content="{{product.name}} | Dokanharu">
<meta name="description" content="{{product.description}}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:title" content="{{product.name}} | Dokanharu">
<meta property="og:description" content="{{product.description}}">
<meta property="og:image" content="https://dokanharu.com/{{product.main_image.url}}">

{% endblock meta %}


{% block content %}
<section class="shop-single-page">
    <div class="container">
        <div class="heading-sub">
            <h3 class="pull-left">Product Detail</h3>
            <ul class="other-link-sub pull-right">
                <li><a href="/">Home</a></li>
                <li><a class="active" href="#detail">{{product.name}}</a></li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="widget-shop-single">
            <div class="row">
                <div class="col-md-5">
                    <div class="shop-single-item-img">
                        <div class="main-img">
                            <div class="main-img-item">
                                <a href="#"><img src="{{product.main_image.url}}" alt="{{product.name}}"
                                        class="img-responsive"></a>
                            </div>
                            {% if product.image1 %}
                            <div class="main-img-item">
                                <a href="#"><img src="{{product.image1.url}}" alt="{{product.name}}"
                                        class="img-responsive"></a>
                            </div>
                            {% endif %}
                            {% if product.image2 %}
                            <div class="main-img-item">
                                <a href="#"><img src="{{product.image2.url}}" alt="{{product.name}}"
                                        class="img-responsive"></a>
                            </div>
                            {% endif %}
                            {% if product.image3 %}
                            <div class="main-img-item">
                                <a href="#"><img src="{{product.image3.url}}" alt="{{product.name}}"
                                        class="img-responsive"></a>
                            </div>
                            {% endif %}
                            {% if product.image4 %}
                            <div class="main-img-item">
                                <a href="#"><img src="{{product.image4.url}}" alt="{{product.name}}"
                                        class="img-responsive"></a>
                            </div>
                            {% endif %}
                        </div>
                        <ul class="multiple-img-list">
                            <li>
                                <div class="product-col">
                                    <div class="img">
                                        <a href="#"><img src="{{product.main_image.url}}" alt="{{product.name}}"
                                                class="img-responsive"></a>
                                    </div>
                                </div>
                            </li>
                            {% if product.image1 %}
                            <li>
                                <div class="product-col">
                                    <div class="img">
                                        <a href="#"><img src="{{product.image1.url}}" alt="{{product.name}}"
                                                class="img-responsive"></a>
                                    </div>
                                </div>
                            </li>
                            {% endif %}
                            {% if product.image2 %}
                            <li>
                                <div class="product-col">
                                    <div class="img">
                                        <a href="#"><img src="{{product.image2.url}}" alt="{{product.name}}"
                                                class="img-responsive"></a>
                                    </div>
                                </div>
                            </li>
                            {% endif %}
                            {% if product.image3 %}
                            <li>
                                <div class="product-col">
                                    <div class="img">
                                        <a href="#"><img src="{{product.image3.url}}" alt="{{product.name}}"
                                                class="img-responsive"></a>
                                    </div>
                                </div>
                            </li>
                            {% endif %}
                            {% if product.image4 %}
                            <li>
                                <div class="product-col">
                                    <div class="img">
                                        <a href="#"><img src="{{product.image4.url}}" alt="{{product.name}}"
                                                class="img-responsive"></a>
                                    </div>
                                </div>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="shop-sing-item-detail">
                        <h3><a href="#">
                                {{product.name}}
                            </a></h3>
                        <div class="brandname">by <strong><a
                                    href="{{product.shop.get_absolute_url}}">{{product.shop.name}}</a></strong>
                            &nbsp;&nbsp;
                            {% if product.shop.is_trusted %}
                            <span
                                style="color:white;background:#6bce04; padding:3px 4px; border-radius:3px;">Trusted</span>
                            {% endif %}
                        </div>

                        <div class="prod-price">
                            <div class="p-price">
                                {% if product.discounted_price < product.price %}
                                <span class="price old">Rs. {{product.price}}</span>
                                <span class="price">Rs. {{product.discounted_price}}</span>
                                {% else %}
                                <span class="price black">Rs. {{product.price}}</span>
                                {% endif %}
                            </div>
                        </div>

                        <div class="description">
                            {{product.sub_title}}
                        </div>
                        <div>
                            <h5 class="titles">Share this product on:</h5>
                            <br>
                            <ul class="social">
                                <li><a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"
                                        target="_blank"><i class="ion-social-facebook fa-3" aria-hidden="true"></i> </a>
                                </li>

                                <li><a href="https://twitter.com/home?status={{request.build_absolute_uri}}"
                                        target="_blank"><i class="ion-social-twitter fa-3" aria-hidden="true"></i></a>
                                </li>

                            </ul>
                        </div>
                        <br>
                        <div class="group-button">
                            <div class="button-ver2">
                                <a class="link-ver1 addcart-ver2" href="{% url 'orders:order_create' product.pk %}">
                                    <span class="icon"></span>Place Order
                                </a>

                            </div>
                        </div>
                        <div class="product-feature">
                            <ul class="product-feature-1">
                                <li><strong>Instock:</strong> {% if product.in_stock %}Yes{% else %}No{% endif %}</li>
                                <li><strong>Brand:</strong> {{product.brand}}</li>
                            </ul>
                            <ul class="product-feature-2">
                                <li><strong>SKU:</strong> {{product.sku}}</li>
                                <li><strong>Category:</strong> {{product.category}}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="product-detail-bottom">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#desc">Description</a></li>
                </ul>
                <div class="tab-content padding-lr">
                    <div id="desc" class="tab-pane fade in active">
                        <br>
                        {{product.description}}
                    </div>

                </div>
            </div>
        </div>
        <br>
        <br>
        <section class="featured-product">
            <div class="container">
                <div class="heading-v1">
                    <h3>MORE PRODUCT BY <a style="color:#6bce04;"
                            href="{{product.shop.get_absolute_url}}">{{product.shop.name}}</a></h3>

                    <div class="clearfix"></div>
                </div>
                <div class="tab-content">
                    <div id="all" class="tab-pane fade in active">
                        <div class="prod-fea-list">
                            <div class="row">
                                {% for product in shop_products %}
                                {% include 'partials/_product.html' with type='featured' %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br>
        <br>
    </div>
</section>
{% endblock content %}

templates/products/product_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Update Dokan
{% endblock title %}

{% block content %}
<div class="container text-center my-5">
    <br>
    <br>
    <h1 class="my-2">Update your Brand</h1>

    <br>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if request.user.id == product.shop.id %}
            <div class="card">
                <form enctype="multipart/form-data" method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Update Product" class="btn-order py-0">
                </form>
                <br>

            </div>
            {% else %}
            <h4>You can't perform this action. Please contact the website administrator.</h4>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}