config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('control-admin/', admin.site.urls),
    path('', include('shops.urls', namespace="shops")),
    path('summernote/', include('django_summernote.urls')),
    path('products/', include('products.urls', namespace="products")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('account/', include('users.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('info/', include('core.urls', namespace="core")),
    path('about/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import dashboard

app_name = "core"

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"),
]

shops/urls.py
from django.urls import path
from . import views

app_name = 'shops'

urlpatterns = [
    path('', views.HomePageView.as_view(), name="home"),
    path('shops/', views.AllShopsView.as_view(), name="all-shops"),
    path('shops/detail/<slug:name>/',
         views.ShopDetailView.as_view(), name="shop-detail"),
    path('shops/create/',
         views.ShopCreateView.as_view(), name="create-shop"),
    path('shops/hide/<int:pk>/', views.hide_shop, name="hide-shop"),
    path('shops/activate/<int:pk>/', views.activate_shop, name="activate-shop"),
    path('shops/edit/<int:pk>', views.ShopEditView.as_view(), name="edit-shop"),
    path('shop/created/', views.ShopCreatedView.as_view(), name="shop-created"),
]

shops/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from core.compress import compress


class Banner(models.Model):
    title = models.CharField(max_length=50)
    link = models.URLField(max_length=240)
    image = models.ImageField(upload_to="banners/")
    block = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id', ]


class Category(models.Model):
    title = models.CharField(max_length=90)
    slug = models.SlugField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Shop(models.Model):
    name = models.CharField(max_length=120)
    address = models.CharField(max_length=100, default="")
    owner = models.OneToOneField("users.User",  on_delete=models.CASCADE)
    category = models.ForeignKey(
        "shops.Category", related_name="shops", on_delete=models.DO_NOTHING, null=True)
    pan_number = models.CharField(max_length=90, default="")
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(
        upload_to='shops/', null=True)
    slug = models.SlugField()
    block = models.BooleanField(default=False)
    hide = models.BooleanField(default=False)
    is_trusted = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    limited = models.BooleanField(default=True)
    date_added = models.DateField(default=timezone.now, null=True)

    class Meta:
        verbose_name_plural = "Shops"
        ordering = ("-id",)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        try:
            shop = Shop.objects.get(pk=self.pk)
        except Shop.DoesNotExist:
            self.slug = slugify(self.name)
        if self.image:
            self.image = compress(self.image)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("shops:shop-detail", kwargs={"name": self.slug})

shops/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View, generic
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models
from products.models import Product
from users.models import User
from shops.models import Shop, Banner, Category
from django.contrib import messages


def hide_shop(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    if shop.owner.id == request.user.id:
        shop.hide = True
        shop.save()
        messages.success(
            request, f'Your Dokan was successfully hid. You can activate it later!')
    return redirect(reverse('core:dashboard'))


def activate_shop(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    if shop.owner.id == request.user.id:
        shop.hide = False
        shop.save()
        messages.success(
            request, f'Your Dokan is activated again!')
    return redirect(reverse('core:dashboard'))


class ShopCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Shop
    fields = ["name", "address", "category",
              "pan_number", "description", "image"]
    success_url = "shops:shop-created"
    template_name = "shops/shop_create.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = User.objects.get(pk=self.request.user.pk)
        self.object.owner = user
        user.is_seller = True
        user.save()
        self.object.save()
        messages.success(
            self.request, f'Your new Dokan was successfully added to Dokanharu.')
        return redirect(reverse(self.success_url))


class ShopEditView(LoginRequiredMixin, generic.UpdateView):
    model = models.Shop
    fields = ["name", "address", "category",
              "pan_number", "description", "image"]
    success_url = "core:dashboard"
    template_name = "shops/shop_edit.html"

    def form_valid(self, form):
        form.save()
        messages.success(
            self.request, f'Your Dokan is successfully edited')
        return redirect(reverse(self.success_url))


class HomePageView(View):
    def get(self, request):

        featured_products = Product.objects.filter(
            featured=True).filter(block=False)
        featured_shops = Shop.objects.filter(
            featured=True).filter(block=False)
        newest_products = Product.objects.filter(block=False)[:30]
        banners = Banner.objects.all().filter(block=False)
        context = {
            "featured_products": featured_products,
            "newest_products": newest_products,
            "banners": banners,
            "featured_shops": featured_shops,

        }
        return render(request, 'shops/index.html', context)


class ShopCreatedView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'shops/shop_created.html')


class AllShopsView(generic.ListView):
    template_name = "shops/shop_list.html"
    context_object_name = "shops"
    paginate_by = 60

    def get_queryset(self):
        category = self.request.GET.get('category', 'all')
        shops = Shop.objects.all().filter(
            hide=False).filter(block=False).order_by('-id')
        if category != "all":
            try:
                item = get_object_or_404(Category, slug=category)
                shops = shops.filter(category=item)

            except Exception:
                pass
        return shops

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context["categories_list"] = categories
        context['category'] = self.request.GET.get('category', 'all')
        return context


class ShopDetailView(generic.ListView):
    model = Shop
    template_name = "shops/shop_detail.html"
    context_object_name = 'products'
    paginate_by = 20

    def get_queryset(self):
        shop = get_object_or_404(Shop, slug=self.kwargs['name'])
        products = shop.products.all()
        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shop"] = get_object_or_404(Shop, slug=self.kwargs['name'])
        return context

templates/shops/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Dokanharu
{% endblock title %}


{% block meta %}

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:title" content="Trade Nepal | Choose your perfect Brand">
<meta property="og:description" content="TradeNpl.com is a platform to get products of your desire Brand and promote your Brand.
">
<meta property="og:image" content="https://dokanharu.com/media/shops/shops/shops/7.jpg">

{% endblock meta %}

{% block content %}
<section class="slide">
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-9 col-sm-12 col-xs-12">
                <div class="row top-row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-item js-banner">

                            {% for banner in banners %}
                            <div class="slide-img">
                                <img src="{{banner.image.url}}" alt="images" class="img-reponsive">
                                <div class="slide-content ver2">
                                    <!--<h5 class="brand" style="color:white;"></h5>-->
                                    <h2 style="color:white;"></h2>
                                </div>
                                <a href="{{banner.link}}" class="slide-button">Get the Link</a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="container-fluid">
                        <div class="jumbotron">
                            <h3 style="color:rgb(34, 133, 199)">Brand awareness </h3>
                            <br> <button type="button" style="background-color: rgb(21, 122, 180);">                   
                            <a style="size: 20px; color:rgb(255, 255, 255)" href="{% url 'shops:create-shop' %}"  >Register your Brand </a></button>  
                            &nbsp;&nbsp;
                            <button>
                            <a href="{% url 'shops:all-shops' %}" title="Marketplace">View Brands</a></button>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sub-banner"><div style="padding-left: 100px;"><img style="align-content: right;" sizes="50%" src="{% static 'img/search.gif' %}" alt="search your brand"></div> </div>
</section>
<br>
<br>
<br>
<section class="featured-product">
    <div class="container">
        <div class="heading-v1">
            <h3 class="pull-left">featured products</h3>

            <div class="clearfix"></div>
        </div>
        <div class="tab-content">
            <div id="all" class="tab-pane fade in active">
                <div class="prod-fea-list">
                    <div class="row">
                        {% for product in featured_products %}
                        {% include 'partials/_product.html' with type='featured' %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="popular-product">
    <div class="container">
        <div class="row">
            <div class="col-md-7 col-sm-7 col-xs-12">
                <div class="heading-v2">
                    <ul class="breadcrumb-ver1">
                        <li class="active"><a data-toggle="pill" href="#popular">Latest Products</a></li>
                    </ul>
                </div>
                <div class="tab-content">
                    <div id="popular" class="tab-pane fade in active">
                        <div class="pp-list">
                            <div class="row top-row">
                                {% for product in newest_products %}
                                {% include 'partials/_product.html' with type='newest' %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <div class="col-md-5 col-sm-5 col-xs-12">
                <aside class="widget brand-v1">
                    <div class="heading-v1">
                        <h3>Featured Brand</h3>
                    </div>
                    <div class="brand-list-v1">

                        {% for shop in featured_shops %}
                        <div class="product-item ver1 bd-style">
                            <div class="prod-item-img">
                                <a href="{{shop.get_absolute_url}}"><img src="{{shop.image.url}}" alt="images" class="img-responsive"></a>
                            </div>
                            <div class="prod-info">
                                <h3><a href="{{shop.get_absolute_url}}" class="price black">{{shop.name}}</a></h3>
                                <div class="p-price">
                                    <span class="black">{{shop.address}}</span>
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/shops/shop_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Dokan
{% endblock title %}

{% block content %}
<div class="container text-center my-5">
    <br>
    <br>
    <h1 class="my-2">Apply to create your own Dokan</h1>

    <br>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <p>Please enter valid details of the dokan that you are creating!</p>
            <br>
            {% if not request.user.is_seller == True %}
            <div class="card">
                <form enctype="multipart/form-data" method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Create Dokan" class="btn-order py-0">
                </form>
                <br>

            </div>
            {% else %}
            <h4>You are already a seller and can't create any shop now. Please contact the website administrator.</h4>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/shops/shop_created.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Dokan Created
{% endblock title %}
{% block content %}
<section class="checkout-page">
    <div class="container">
        <div class="heading-sub">
            <h3 class="pull-left">Shop Created</h3>
            <ul class="other-link-sub pull-right">
                <li><a href="/">Home</a></li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="complete-page text-center">
            {% if request.user.is_seller == True %}
            <h2 class="status">
                <span class="ion-checkmark-circled fa-4 icon-check"></span>
                Congratulations! You have became a <span>seller</span>
            </h2>
            <br>
            <p class="lead my-2">
                You can manage your Dokan and start adding products from the dashboard.
            </p>
            <h5><a href="{% url 'core:dashboard' %}">Go to Dashboard</a></h5>
            {% else %}
            <h2>
                Page not found
            </h2>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

templates/shops/shop_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{shop.name}} | Brands
{% endblock title %}

{% block meta %}
    <!-- Primary Meta Tags -->
<meta name="title" content="{{shop.name}} | Dokanharu">
<meta name="description" content="{{shop.description}}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:title" content="{{shop.name}} | Dokanharu">
<meta property="og:description" content="{{shop.description}}">
<meta property="og:image" content="https://dokanharu.com{{shop.image.url}}">

{% endblock meta %}

{% block content %}
<br>
<br>
<div class="container">
    <div class="heading-v1">
        <h3 class="pull-left">About Brand</h3>

        <div class="clearfix"></div>
    </div>
    <br>

</div>
<div class="container">

    <div class="row">
        <div class="col-md-4">
            <img src="{{shop.image.url}}" alt="{{shop.name}}" class="img-responsive">
        </div>
        <div class="col-md-8">
            <h2>{{shop.name}} </h2>
            <br>
            <p>{% if shop.is_trusted %} 
                <span style="color:white;background:#ffffff; padding:3px 4px; border-radius:3px;"><img src="{% static 'img/trust.png' %}"></span>
                {% endif %}</p>
            <br>
            <h5>- {{shop.category}} Brand</h5>
            <h5>Dealer Address - {{shop.address}}</h5>
            <h5>PAN Number - {{shop.pan_number}}</h5>
            <h5>Phone Number - {{shop.owner.phone}}</h5>
            <br>
            <p>{{shop.description}}</p>
            <br>
            <div>
                <h5 class="titles">Share this Brand on:</h5>
                <br>
                <ul class="social">
                    <li><a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"
                            target="_blank"><i class="ion-social-facebook fa-3" aria-hidden="true"></i> </a>
                    </li>

                    <li><a href="https://twitter.com/home?status={{request.build_absolute_uri}}" target="_blank"><i
                                class="ion-social-twitter fa-3" aria-hidden="true"></i></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</div>
<br>
<br>
<section class="featured-product">
    <div class="container">
        <div class="heading-v1">
            <h3 class="pull-left">All products of  {{shop.name}} Brands</h3>

            <div class="clearfix"></div>
        </div>
        <div class="tab-content">
            <div id="all" class="tab-pane fade in active">
                <div class="prod-fea-list">
                    <div class="row">
                        {% for product in products %}
                        {% include 'partials/_product.html' with type='featured' %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="product-pagination">
            {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li><a href="?sort={{request.GET.sort}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
                {% else %}
                <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                <li><a href="?sort={{request.GET.sort}}&page={{ i }}">{{ i }}</a>
                </li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="?sort={{request.GET.sort}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
                {% else %}
                <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</section>

{% endblock content %}

templates/shops/shop_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Update Dokan
{% endblock title %}

{% block content %}
<div class="container text-center my-5">
    <br>
    <br>
    <h1 class="my-2">Update your Dokan</h1>

    <br>
</div>
<br>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if request.user.id == shop.owner.id %}
            <div class="card">
                <form enctype="multipart/form-data" method="POST">
                    {{ form | crispy }}
                    {% csrf_token %}
                    <input type="submit" value="Update Dokan" class="btn-order py-0">
                </form>
                <br>

            </div>
            {% else %}
            <h4>You can't perform this action. Please contact the website administrator.</h4>
            {% endif %}
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/shops/shop_list.html
{% extends 'base.html' %}
{% load static %}
{% load remove_dash %}

{% block title %}
All Brands
{% endblock title %}

{% block content %}
<section class="shop-list-v3-page">
    <div class="container">
        <div class="heading-sub">
            <h3 class="pull-left">All Brands List</h3>
            <div class="clearfix"></div>
        </div>

        <div class="widget-product-list">
            <div class="row">

                <div class="col-md-12">
                    <div class="filter-block bd" style="padding-top:0 !important;">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="box box-view">

                                    <div class="box sort pull-right">
                                        <span>Change Category:</span>
                                        <button class="dropdown-toggle" type="button" data-toggle="dropdown" id="menu2">
                                            <span class="dropdown-label">{{category|title|remove_dash}}</span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu" aria-labelledby="menu2">
                                            <li><a href="{% url 'shops:all-shops' %}" title="">All</a>
                                            </li>
                                            {% for category in categories_list %}

                                            <li><a href="{% url 'shops:all-shops' %}?category={{category.slug}}"
                                                    title="">{{category.title}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-7 margin-top3">

                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <div class="">
                        <div class="prod-fea-list">
                            <div class="row">
                                {% for shop in shops %}
                                {% include 'partials/_shop.html' %}
                                {% endfor %}
                            </div>
                            <div class="product-pagination">
                                {% if is_paginated %}
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                    <li><a
                                            href="?sort={{request.GET.sort}}&page={{ page_obj.previous_page_number }}">&laquo;</a>
                                    </li>
                                    {% else %}
                                    <li class="disabled"><span>&laquo;</span></li>
                                    {% endif %}
                                    {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                    {% else %}
                                    <li><a href="?sort={{request.GET.sort}}&page={{ i }}">{{ i }}</a>
                                    </li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li><a
                                            href="?sort={{request.GET.sort}}&page={{ page_obj.next_page_number }}">&raquo;</a>
                                    </li>
                                    {% else %}
                                    <li class="disabled"><span>&raquo;</span></li>
                                    {% endif %}
                                </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock content %}